<a href="https://colab.research.google.com/github/MeghanaPidaparthi/ExcelR-assignments/blob/main/Day_9.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

In [4]:
a=[30,48,289,45,26,84,81,77,22,93,49,59,84,96,20,11,47]
a
type(a)

list

In [5]:
a

[30, 48, 289, 45, 26, 84, 81, 77, 22, 93, 49, 59, 84, 96, 20, 11, 47]

In [6]:
a[-2:-10:-1]

[11, 20, 96, 84, 59, 49, 93, 22]

In [8]:
np.random.seed(94)
b= np.random.randint(15,50,(7,8))
b

array([[33, 15, 18, 37, 44, 34, 31, 23],
       [31, 29, 48, 25, 47, 39, 39, 18],
       [30, 41, 26, 21, 28, 29, 17, 38],
       [49, 47, 16, 15, 48, 22, 44, 35],
       [23, 30, 25, 34, 42, 16, 39, 35],
       [45, 45, 21, 45, 37, 48, 23, 47],
       [30, 37, 37, 17, 45, 24, 44, 39]])

In [9]:
b

array([[33, 15, 18, 37, 44, 34, 31, 23],
       [31, 29, 48, 25, 47, 39, 39, 18],
       [30, 41, 26, 21, 28, 29, 17, 38],
       [49, 47, 16, 15, 48, 22, 44, 35],
       [23, 30, 25, 34, 42, 16, 39, 35],
       [45, 45, 21, 45, 37, 48, 23, 47],
       [30, 37, 37, 17, 45, 24, 44, 39]])

In [11]:
b[:,-1] #last column

array([23, 18, 38, 35, 35, 47, 39])

In [12]:
b[6,4]

45

In [13]:
b[1:5]

array([[31, 29, 48, 25, 47, 39, 39, 18],
       [30, 41, 26, 21, 28, 29, 17, 38],
       [49, 47, 16, 15, 48, 22, 44, 35],
       [23, 30, 25, 34, 42, 16, 39, 35]])