<a href="https://colab.research.google.com/github/MeghanaPidaparthi/ExcelR-assignments/blob/main/Day_8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [6]:
a = np.random.randint(0,10,10)

In [7]:
a

array([8, 5, 8, 9, 5, 4, 6, 9, 4, 7])

In [14]:
np.random.seed(234)

In [15]:
arr = np.random.randint(20,99,(6,7))

In [16]:
arr

array([[92, 51, 88, 77, 53, 23, 74],
       [83, 87, 54, 74, 28, 59, 91],
       [52, 79, 84, 46, 91, 43, 23],
       [35, 65, 65, 23, 97, 93, 71],
       [39, 40, 43, 38, 27, 35, 61],
       [23, 93, 60, 93, 75, 43, 98]])

In [17]:
m=[5,20,45,234]

In [18]:
m

[5, 20, 45, 234]

In [21]:
m = [5,10,20,45,234]
for i in range(len(m)):
  m[i]=m[i]**2
m


[25, 100, 400, 2025, 54756]

In [22]:
b=(3,6,7,8,9)
b

(3, 6, 7, 8, 9)

In [26]:
b_list = list(b)

In [29]:
b= tuple(x+5 for x in b)

In [30]:
b

(8, 11, 12, 13, 14)

In [31]:
k=[55,25,85,75,35,45,95]
k

[55, 25, 85, 75, 35, 45, 95]

In [33]:
for i in range(len(k)):
  if(k[i]>50):
    print(k[i])

55
85
75
95


In [34]:
d=[]
for i in k:
  if i<50:
    d.append(i)

In [35]:
d

[25, 35, 45]

In [39]:
arr = [1, 5, 10, 15, 20,99,75,67,98,88,99,12]

In [40]:
arr

[1, 5, 10, 15, 20, 99, 75, 67, 98, 88, 99, 12]

In [46]:
import numpy as np
arr=np.array(arr)
arr[arr < 40]

array([ 1,  5, 10, 15, 20, 12])

In [47]:
arr>50

array([False, False, False, False, False,  True,  True,  True,  True,
        True,  True, False])